-- 1. push_subscriptions テーブル（通知購読テーブル）を作成
-- 既に存在する場合は作成しません
create table if not exists public.push_subscriptions (
    id bigint generated by default as identity primary key,
    -- どのユーザーの購読かを記録（auth.usersテーブルと紐付け）
    user_id uuid references auth.users(id) not null,
    -- ブラウザから受け取った購読情報（エンドポイントやキーなど）をJSON形式で保存
    subscription jsonb not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- 同じユーザーが同じ端末（購読情報）を重複して登録しないように制限
    unique(user_id, subscription) 
);

-- 2. RLS（行レベルセキュリティ）を有効化
-- これにより、許可されたポリシー以外のアクセスを遮断します
alter table public.push_subscriptions enable row level security;

-- 3. ポリシー作成: ユーザーは自分の購読情報のみ操作可能
-- 自分の user_id と一致するデータのみ、登録・参照・更新・削除ができます
create policy "Users can manage their own subscriptions"
on public.push_subscriptions
for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 4. ポリシー作成: サービスロール（管理者権限）は全て操作可能
-- Webhookやサーバーサイド処理で全データにアクセスするために必要です
create policy "Service role can manage all subscriptions"
on public.push_subscriptions
for all
to service_role
using (true)
with check (true);
